[package]
name = "orb-slot-ctrl"
version = "0.3.0"
description = """
The Slot Control is a tool to read and write the slot and rootfs state of the Orb.
"""
authors = ["Mark Eder <mark.eder@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
libc.workspace = true
orb-build-info.path = "../build-info"
thiserror.workspace = true

[build-dependencies]
orb-build-info = { path = "../build-info", features = ["build-script"] }
