[package]
name = "orb-slot-ctrl"
version = "0.3.1"
description = """
The Slot Control is a tool to read and write the slot and rootfs state of the Orb.
"""
authors = ["Mark Eder <mark.eder@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
efivar = { workspace = true }
clap = { workspace = true, features = ["derive"] }
orb-info = { workspace = true, features = ["orb-os-release"]}
color-eyre.workspace = true
libc.workspace = true
orb-build-info.workspace = true
tempfile = "3.12.0"
thiserror.workspace = true
derive_more = { workspace = true,  default-features = false, features = ["display", "from"] }
bon.workspace = true

[dependencies.rustix]
workspace = true
features = [
	"fs",
	"process",
]

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[package.metadata.deb]
assets = [
  ["warn_renamed.sh", "/usr/bin/orb-slot-ctrl", "755"],
  ["target/release/orb-slot-ctrl", "/usr/local/bin/", "755"]
]

[features]
test = []

[package.metadata.orb]
unsupported_targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
