[package]
name = "orb-bidiff-squashfs"
version = "0.0.0"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bidiff.workspace = true
orb-bidiff-squashfs-shim.workspace = true
