[package]
name = "orb-cone"
version = "0.0.0"
authors = ["Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre.workspace = true
embedded-graphics = "0.8.1"
ftdi-embedded-hal.workspace = true
futures.workspace = true
gc9a01-rs = "0.2.1"
image = { version = "=0.25.8", features = [] }
orb-rgb = { path = "../rgb" }
qrcode = "0.14.1"
rand = "0.8.5"
thiserror.workspace = true
tinybmp = "0.5.0"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
