[package]
name = "seek-camera-sys"
version = "0.0.0"
edition = "2021"
publish = false
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"

[dependencies]

[build-dependencies]
bindgen.workspace = true
color-eyre.workspace = true
convert_case = "0.6"
