[package]
name = "orb-uart"
version = "0.0.3"
authors = ["Valentine Valyaeff <valentyn.valiaiev@toolsforhumanity.com>, Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"]
edition = "2021"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"

[dependencies]
libc = "0.2"
log = "0.4"
