[package]
name = "orb-uart"
version = "0.0.0"
authors = [
    "Valentine Valyaeff <valentyn.valiaiev@toolsforhumanity.com>",
    "Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"
]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
libc = "0.2"
log = "0.4"
