[package]
name = "orb-qr-link"
version = "0.0.4"
description = "Data link between Worldcoin App and Orb through QR-codes"
authors = ["Valentyn Valiaiev <valentyn.valiaiev@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["encode", "decode"]
decode = []
encode = []

[dependencies]
blake3 = "1.5.0"
data-encoding = "2.4.0"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.57"
uuid = { version = "1.4.1", features = ["v4"] }

[[test]]
name = "verification"
required-features = ["encode", "decode"]
