[package]
name = "orb-thermal-cam-ctrl"
version = "0.0.5"
description = "CLI util for the thermal camera on the orb"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
clap = { version = "4.3", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6"
indicatif = "0.17"
orb-build-info.path = "../build-info"
owo-colors = "3"
png = "0.17"
seek-camera.path = "../seek-camera/wrapper"

[build-dependencies]
orb-build-info = { path = "../build-info", features = ["build-script"] }
color-eyre = "0.6.2"
