[package]
name = "pid"
version = "0.0.4"
edition = "2021"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
