[package]
name = "orb-backend-status"
version = "0.0.1"
description = "Systemd service that receives orb status and periodicallyprovides it to the Orb backend"
authors = ["Paul Quinn <paulquinn00@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["linux-collectors"]
linux-collectors = [
	"dep:orb-backend-status-dbus",
	"dep:orb-connd-dbus",
	"dep:orb-endpoints",
	"dep:orb-messages",
	"orb-telemetry/zbus-tracing",
	"dep:orb-update-agent-dbus",
	"dep:zbus",
	"orb-info/orb-token",
]
android-collectors = ["dep:clap"]

[[bin]]
name = "orb-backend-status"
path = "src/main.rs"

[dependencies]
bon.workspace = true
clap = { workspace = true, optional = true }
chrono = { workspace = true, features = ["serde"] }
color-eyre.workspace = true
derive_more = { workspace = true, default-features = false, features = ["from"] }
flume.workspace = true
futures-util = { version = "0.3.31" }
eyre.workspace = true
oes.workspace = true
orb-backend-status-dbus = { workspace = true, optional = true }
orb-build-info.workspace = true
orb-connd-dbus = { workspace = true, optional = true }
orb-endpoints = { workspace = true, optional = true }
orb-messages = { workspace = true, optional = true }
orb-info = { workspace = true, features = [
	"async",
	"orb-id",
	"orb-jabil-id",
	"orb-name",
	"orb-os-release",
] }
orb-dogd.workspace = true
orb-security-utils = { workspace = true, features = ["reqwest"] }
orb-telemetry = { workspace = true, features = ["otel"] }
orb-update-agent-dbus = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { version = "0.4.1", features = ["json"] }
reqwest-tracing = { version = "0.5.6", features = ["opentelemetry_0_27"] }
reqwest-retry = "0.7.0"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { version = "3.11.0" }
tempfile.workspace = true
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = [
	"io-util",
	"macros",
	"net",
	"rt-multi-thread",
	"sync",
] }
tokio-util.workspace = true
tracing = { workspace = true, features = ["attributes"] }
zbus = { workspace = true, optional = true, default-features = false, features = [
	"tokio",
] }
zenorb.workspace = true

[dev-dependencies]
orb-info = { workspace = true, features = ["testing"] }
orb-dogd = { workspace = true, features = ["testing"] }
orb-security-utils = { workspace = true, features = [
	"reqwest",
	"dangerously-allow-http",
] }
dbus-launch.workspace = true
eyre.workspace = true
portpicker = "0.1.1"
proptest.workspace = true
serial_test.workspace = true
tempfile = "3.10.1"
tokio.workspace = true
wiremock = { version = "0.6.3" }
zbus.workspace = true
zbus_systemd.workspace = true
orb-update-agent-dbus.workspace = true
async-tempfile.workspace = true

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[package.metadata.deb]
assets = [["target/release/orb-backend-status", "/usr/local/bin/", "755"]]
maintainer-scripts = "debian/"
systemd-units = [{ unit-name = "worldcoin-backend-status" }]
