[package]
name = "orb-pcp-defs"
version = "0.0.0"
description = "Protobuf definitions for Personal Custody Package messages."

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pbjson = "0.9.0"
prost = { version = "0.14.1", default-features = false, features = ["std", "derive"] }
serde.workspace = true

[dev-dependencies]
flate2.workspace = true
serde_json.workspace = true
tar.workspace = true

[build-dependencies]
pbjson-build = "0.9.0"
prost-build = "0.14.1"
