[package]
name = "seek-camera"
version = "0.0.0"
description = "Safe rust bindings for the seek thermal camera SDK"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = "1.14"
fixed = "1.23.1"
log = "0.4"
seek-camera-sys.path = "../sys"
thiserror = "1"

[dev-dependencies]
rusty-fork = "0.3"
tempfile = "3.9"

[package.metadata.orb]
unsupported_targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]
