[package]
name = "orb-pcp"
version = "0.1.0"
description = "Personal Custody Package construction primitives"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
not-prod-diagnostics = []

[dependencies]
data-encoding.workspace = true
flate2.workspace = true
hyrax = { git = "https://github.com/worldcoin/hyrax-pcs-commit.git", rev = "ec5f1120e394643ad09990a34815dd11e9122366" }
orb-pcp-defs = { path = "../pcp-defs/rust" }
rand.workspace = true
ring.workspace = true
serde_json.workspace = true
sodiumoxide.workspace = true
tar.workspace = true
thiserror.workspace = true
zeroize = "1"

[dev-dependencies]
p256.workspace = true
