[package]
name = "verity-tree-calc"
version = "0.0.4"
description = "Utility CLI tool for verity tree scripts in orb-os"
authors = ["Galileo Daras <galileo.daras@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
build-info.path = "../build-info"
clap = { version = "4", features = ["derive"] }
tracing = "0.1.0"
tracing-subscriber = "0.3"

[build-dependencies]
build-info = { path = "../build-info", features = ["build-script"] }
