[package]
name = "orb-zbus-proxies"
version = "0.0.0"
description = "Blocking Zbus proxies for third party services"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
login1 = []

[dependencies]
thiserror.workspace = true
tracing.workspace = true
zbus = { workspace = true, default-features = false }
