[package]
name = "orb-supervisor"
version = "0.5.0"
description = "Privileged daemon that supervises the orb"
authors = [
	"Richard Janis Goldschmidt",
	"Galileo Daras <galileo@getcoffee.io>",
]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
futures.workspace = true
libc.workspace = true
listenfd = "1.0.0"
once_cell = "1.15.0"
orb-build-info.workspace = true
tap = "1.0.1"
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = "0.1.11"
tracing = { workspace = true, features = ["attributes"] }
tracing-journald.workspace = true
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
zbus = { version = "3.9.0", default-features = false, features = ["tokio"] }
zbus_systemd = { version = "0.0.8", features = [ "systemd1", "login1" ] }

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[dev-dependencies]
dbus-launch = "0.2.0"
tokio = { version = "1.25.0", features = ["sync", "test-util"] }

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [
  ["target/release/orb-supervisor", "/usr/local/bin/", "755"]
]
systemd-units = [
  { unit-name = "worldcoin-supervisor" },
]
