[package]
name = "orb-ui"
version = "0.0.4"
edition = "2021"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orb-uart.path = "uart"
pid.path = "pid"
tokio = { version = "1", features = ["full"] }
futures = "0.3.29"
eyre = "0.6"
prost = "0.12.3"
orb-mcu-messaging = { git = "https://github.com/worldcoin/orb-mcu-messaging.git", rev = "373914af23e3ab33a6ef0f64d3a6e3f39d75a8ab" }
zbus = { version = "3", default-features = false, features = ["tokio"] }
serde = { version = "1.0.190", features = ["derive"] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
async-trait = "0.1.74"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
dashmap = "5.5.3"
clap = { version = "4.4", features = ["derive"] }
rodio = "0.17.3"
derive_more = { version = "0.99", default-features = false, features = ["display", "from"] }
serde_json = "1.0.108"

[build-dependencies]
prost-build = "0.12.3"

[[example]]
name = "dbus-client"
path = "examples/dbus-client.rs"
