[package]
name = "orb-ui"
version = "0.0.1"
description = "Systemd daemon responsible for running the UI on the orb."
authors = ["Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.74"
clap.workspace = true
dashmap = "5.5.3"
derive_more.workspace = true
eyre.workspace = true
futures.workspace = true
orb-messages.workspace = true
orb-sound.path = "sound"
orb-uart.path = "uart"
pid.path = "pid"
prost = "0.12.3"
serde.workspace = true
serde_json = "1.0.108"
tokio.workspace = true
tokio-stream = "0.1.14"
tracing.workspace = true
tracing-subscriber.workspace = true
zbus.workspace = true

[target.'cfg(tokio_unstable)'.dependencies]
console-subscriber.workspace = true

[build-dependencies]
prost-build = "0.12.3"

[[example]]
name = "ui-replay"
path = "examples/ui-replay.rs"

# dependencies for the dbus-client example
[dev-dependencies]
chrono = "0.4.35"

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = [
  { unit-name = "worldcoin-ui" },
]
