[package]
name = "orb-ui"
version = "0.0.3"
description = "Systemd daemon responsible for running the UI on the orb."
authors = ["Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.74"
clap.workspace = true
dashmap = "5.5.3"
derive_more.workspace = true
eyre.workspace = true
futures.workspace = true
orb-build-info.path = "../build-info"
orb-messages.workspace = true
orb-rgb.path = "rgb"
orb-sound.path = "sound"
orb-uart.path = "uart"
pid.path = "pid"
prost = "0.12.3"
rand = "0.8.5"
serde.workspace = true
serde_json = "1.0.108"
tokio-stream = "0.1.14"
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
zbus.workspace = true

[target.'cfg(tokio_unstable)'.dependencies]
console-subscriber.workspace = true

[build-dependencies]
orb-build-info = { path = "../build-info", features = ["build-script"] }

[[example]]
name = "ui-replay"
path = "examples/ui-replay.rs"

# dependencies for the dbus-client example
[dev-dependencies]
chrono = "0.4.35"

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [
  ["sound/assets/*.wav", "/home/worldcoin/data/sounds/", "644"]
]
systemd-units = [
  { unit-name = "worldcoin-ui" },
]

[package.metadata.orb]
unsupported_targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(tokio_unstable)']
