[package]
name = "orb-ui"
version = "0.0.4"
description = "Systemd daemon responsible for running the UI on the orb."
authors = ["Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4", features = ["derive"] }
dashmap = "5.5.3"
derive_more = { version = "0.99", default-features = false, features = ["display", "from"] }
eyre = "0.6"
futures = "0.3.29"
orb-mcu-messaging.workspace = true
orb-uart.path = "uart"
pid.path = "pid"
prost = "0.12.3"
rodio = "0.17.3"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
zbus = { version = "4", default-features = false, features = ["tokio"] }

[build-dependencies]
prost-build = "0.12.3"

[[example]]
name = "dbus-client"
path = "examples/dbus-client.rs"
