[package]
name = "orb-google-geolocation-api"
version = "0.0.0"
authors = ["Galileo Daras <galileo@getcoffee.io>"] 
description = "Google geolocation apis"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["cellcom", "wpa-supp"]
wpa-supp = ["dep:orb-location-wpa-supplicant"]
cellcom = ["dep:orb-cellcom"]

[dependencies]
bon.workspace = true
eyre.workspace = true
orb-cellcom = { workspace = true, features = ["serde"], optional = true }
orb-location-wpa-supplicant = { workspace = true, optional = true }
reqwest = { workspace = true, default-features = false, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
