//! Synchronous PCP construction from portable inputs.
//!
//! PNG encoding, quantization, secret sharing and signer/recipient authorization
//! belong to the caller. Generated Hyrax commitments use the legacy algorithm;
//! imported commitments and partial-data wire semantics are not supported here.
//! This prototype is not an untrusted-package verifier. Call from a blocking
//! worker in async applications. Plaintext intermediates are not all zeroized.

use std::collections::BTreeMap;

use rand::{CryptoRng, RngCore};

use crate::{archive, di, encryption, inner, layout, manifest, metadata, payload};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Version {
    V2_7,
    V2_8,
    V3_0,
}

/// Shares are generated by the consumer. Each array has exactly three recipients.
pub struct IrisShares<'a> {
    pub version: &'a str,
    pub left_iris: [&'a str; 3],
    pub left_mask: [&'a str; 3],
    pub right_iris: [&'a str; 3],
    pub right_mask: [&'a str; 3],
}

pub struct Included<'a> {
    pub images: inner::Images<'a>,
    pub thumbnail_image_id: Option<&'a str>,
    pub left_iris_code_aggregate_image_ids: &'a [&'a str],
    pub right_iris_code_aggregate_image_ids: &'a [&'a str],
    pub face_embeddings: &'a [payload::FaceEmbedding<'a>],
    pub iris_codes: payload::IrisCodes<'a>,
    pub iris_shares: IrisShares<'a>,
    pub di_left: Option<&'a di::Eye<'a>>,
    pub di_right: Option<&'a di::Eye<'a>>,
    pub di_shares_version: &'a str,
}

/// One privacy decision controls files, manifest hashes and metadata image IDs.
pub enum Biometrics<'a> {
    Redacted,
    Included(&'a Included<'a>),
}

pub struct Request<'a> {
    pub version: Version,
    /// Whole Unix seconds used for archive and gzip headers.
    pub timestamp: u64,
    pub info: metadata::Info<'a>,
    pub user_public_key: &'a [u8; 32],
    /// These same public keys are serialized and used for inner encryption.
    pub backend_keys: payload::BackendKeys<'a>,
    pub biometrics: Biometrics<'a>,
}

/// Final encrypted tiers and SHA-256 checksums of those ciphertext bytes.
pub struct Package {
    pub tier0: Vec<u8>,
    pub tier1: Vec<u8>,
    pub tier2: Vec<u8>,
    pub tier0_checksum: [u8; 32],
    pub tier1_checksum: [u8; 32],
    pub tier2_checksum: [u8; 32],
}

#[derive(Debug, thiserror::Error)]
pub enum Error<E> {
    #[error("device key presence does not match the requested PCP version")]
    DeviceKeyVersionMismatch,
    #[error("duplicate package hash name")]
    DuplicateHash,
    #[error("metadata construction failed")]
    Metadata(#[from] metadata::Error),
    #[error("inner archive construction failed")]
    Inner(#[from] inner::Error),
    #[error("payload serialization failed")]
    Json(#[from] serde_json::Error),
    #[error("DI encoding failed")]
    Di(#[from] di::Error),
    #[error("archive encoding failed")]
    Archive(#[from] archive::Error),
    #[error("encryption failed")]
    Encryption(#[from] encryption::Error),
    #[error("manifest signing failed")]
    Signing(#[from] manifest::SigningError<E>),
}

/// Builds all three tiers, invoking the supplied raw-digest signer once.
/// No successful package is returned on failure. The signer owns its retry and
/// deadline policy. V2.7 requires no device key; V2.8 requires one; V3 accepts
/// either. Version negotiation remains a consumer responsibility.
pub fn build<E>(
    request: &Request<'_>,
    rng: &mut (impl RngCore + CryptoRng),
    sign_digest: impl FnOnce(&[u8; 32]) -> Result<Vec<u8>, E>,
) -> Result<Package, Error<E>> {
    match (request.version, request.info.device_public_key.is_some()) {
        (Version::V2_7, true) | (Version::V2_8, false) => {
            return Err(Error::DeviceKeyVersionMismatch)
        }
        _ => (),
    }
    if request.timestamp > u64::from(u32::MAX) {
        return Err(archive::Error::TimestampOutOfRange.into());
    }
    let format = match request.version {
        Version::V2_7 | Version::V2_8 => layout::Format::V2,
        Version::V3_0 => layout::Format::V3,
    };
    let backend_keys_json = payload::backend_keys(&request.backend_keys)?;
    let mut hashes =
        BTreeMap::from([("backend_keys.json".to_owned(), sha256(&backend_keys_json))]);
    let prepared = match &request.biometrics {
        Biometrics::Redacted => None,
        Biometrics::Included(input) => Some(prepare(input, request, rng)?),
    };
    if let Some(prepared) = &prepared {
        for (name, hash) in &prepared.archives.hashes {
            insert_hash(&mut hashes, name.clone(), *hash)?;
        }
    }
    let biometric_files = prepared.as_ref().map(Prepared::layout);
    let auxiliary =
        layout::auxiliary_tiers(format, request.timestamp, biometric_files.as_ref())?;
    let tier1 = seal_tier(&auxiliary.tier1, request, "tier1.tar.gz")?;
    let tier2 = seal_tier(&auxiliary.tier2, request, "tier2.tar.gz")?;
    let tier1_checksum = sha256(&tier1);
    let tier2_checksum = sha256(&tier2);

    let info = encode_metadata(request, rng)?;
    for (name, hash) in info.hashes {
        insert_hash(&mut hashes, name.to_owned(), hash)?;
    }
    let version = match request.version {
        Version::V2_7 => manifest::Version::V2_7,
        Version::V2_8 => manifest::Version::V2_8,
        Version::V3_0 => manifest::Version::V3_0 {
            tier_1: tier1_checksum,
            tier_2: tier2_checksum,
        },
    };
    let signed = manifest::encode_and_sign(
        version,
        hashes.iter().map(|(name, hash)| (name.as_str(), *hash)),
        sign_digest,
    )?;
    let tier0 = layout::tier0(
        format,
        request.timestamp,
        layout::Tier0Files {
            info_json: &info.info_json,
            hashes_json: &signed.hashes_json,
            hashes_signature: &signed.hashes_signature,
            backend_keys_json: &backend_keys_json,
        },
        biometric_files.as_ref(),
    )?;
    let tier0 = seal_tier(&tier0, request, "tier0.tar.gz")?;
    Ok(Package {
        tier0_checksum: sha256(&tier0),
        tier1_checksum,
        tier2_checksum,
        tier0,
        tier1,
        tier2,
    })
}

struct Prepared {
    archives: inner::Encoded,
    face_embeddings: Vec<u8>,
    iris_codes: Vec<u8>,
    iris_shares: [Vec<u8>; 3],
    di: di::Encoded,
}

impl Prepared {
    fn layout(&self) -> layout::Biometrics<'_> {
        layout::Biometrics {
            archives: layout::BiometricArchives {
                iris_sealed: &self.archives.iris,
                normalized_iris_sealed: &self.archives.normalized_iris,
                face_sealed: &self.archives.face,
                fraud_sealed: self.archives.fraud.as_deref(),
                face_ir_and_thermal: &self.archives.face_ir_and_thermal,
            },
            face_embeddings_json: &self.face_embeddings,
            iris_codes_json: &self.iris_codes,
            iris_code_shares_json: [
                &self.iris_shares[0],
                &self.iris_shares[1],
                &self.iris_shares[2],
            ],
            di_iris_embeddings_pb: &self.di.embeddings,
            di_iris_embeddings_shares_pb: [
                &self.di.shares[0],
                &self.di.shares[1],
                &self.di.shares[2],
            ],
        }
    }
}

fn prepare<E>(
    input: &Included<'_>,
    request: &Request<'_>,
    rng: &mut (impl RngCore + CryptoRng),
) -> Result<Prepared, Error<E>> {
    let mut archives = inner::encode(request.timestamp, &input.images, rng)?;
    archives.iris =
        encryption::seal(&archives.iris, request.backend_keys.iris.public_key)?;
    archives.normalized_iris = encryption::seal(
        &archives.normalized_iris,
        request.backend_keys.normalized_iris.public_key,
    )?;
    archives.face =
        encryption::seal(&archives.face, request.backend_keys.face.public_key)?;
    archives.fraud = archives
        .fraud
        .as_deref()
        .map(|tar| encryption::seal(tar, request.backend_keys.face.public_key))
        .transpose()?;
    if request.version != Version::V3_0 {
        archives.face_ir_and_thermal = encryption::seal(
            &archives.face_ir_and_thermal,
            request.backend_keys.tier2.public_key,
        )?;
    }
    let face_embeddings = payload::face_embeddings(input.face_embeddings)?;
    let iris_codes = payload::iris_codes(&input.iris_codes)?;
    let [share0, share1, share2] = [0, 1, 2].map(|i| {
        payload::iris_code_share(&payload::IrisCodeShare {
            iris_version: input.iris_codes.iris_version,
            iris_shares_version: input.iris_shares.version,
            left_iris_code_shares: input.iris_shares.left_iris[i],
            left_mask_code_shares: input.iris_shares.left_mask[i],
            right_iris_code_shares: input.iris_shares.right_iris[i],
            right_mask_code_shares: input.iris_shares.right_mask[i],
        })
    });
    let iris_shares = [share0?, share1?, share2?];
    let di = di::encode(input.di_left, input.di_right, input.di_shares_version)?;
    for (name, bytes) in [
        ("face_embeddings.json", face_embeddings.as_slice()),
        ("iris_codes.json", iris_codes.as_slice()),
        ("di_iris_embeddings.pb", di.embeddings.as_slice()),
    ] {
        insert_hash(&mut archives.hashes, name.to_owned(), sha256(bytes))?;
    }
    for (i, iris_share) in iris_shares.iter().enumerate() {
        insert_hash(
            &mut archives.hashes,
            format!("iris_code_shares_{i}.json"),
            sha256(iris_share),
        )?;
        insert_hash(
            &mut archives.hashes,
            format!("di_iris_embeddings_shares_{i}.pb"),
            sha256(&di.shares[i]),
        )?;
    }
    Ok(Prepared {
        archives,
        face_embeddings,
        iris_codes,
        iris_shares,
        di,
    })
}

fn encode_metadata(
    request: &Request<'_>,
    rng: &mut (impl RngCore + CryptoRng),
) -> Result<metadata::Encoded, metadata::Error> {
    match &request.biometrics {
        Biometrics::Redacted => {
            metadata::encode(&request.info, &metadata::Images::Redacted, rng)
        }
        Biometrics::Included(input) => {
            let left_ids: Vec<_> = input
                .images
                .left
                .as_ref()
                .into_iter()
                .flat_map(|eye| eye.multiframe.iter().map(|frame| frame.image_id))
                .collect();
            let right_ids: Vec<_> = input
                .images
                .right
                .as_ref()
                .into_iter()
                .flat_map(|eye| eye.multiframe.iter().map(|frame| frame.image_id))
                .collect();
            let images =
                metadata::Images::Included(metadata::ImageIds {
                    left: input.images.left.as_ref().map(|eye| {
                        metadata::IrisImageIds {
                            primary: eye.primary.image_id,
                            multiframe: &left_ids,
                        }
                    }),
                    right: input.images.right.as_ref().map(|eye| {
                        metadata::IrisImageIds {
                            primary: eye.primary.image_id,
                            multiframe: &right_ids,
                        }
                    }),
                    thumbnail: input.thumbnail_image_id,
                    left_iris_code_aggregate: input.left_iris_code_aggregate_image_ids,
                    right_iris_code_aggregate: input
                        .right_iris_code_aggregate_image_ids,
                });
            metadata::encode(&request.info, &images, rng)
        }
    }
}

fn insert_hash<E>(
    hashes: &mut BTreeMap<String, [u8; 32]>,
    name: String,
    hash: [u8; 32],
) -> Result<(), Error<E>> {
    if hashes.insert(name, hash).is_some() {
        return Err(Error::DuplicateHash);
    }
    Ok(())
}

fn seal_tier<E>(
    tar: &[u8],
    request: &Request<'_>,
    name: &str,
) -> Result<Vec<u8>, Error<E>> {
    let gzip = archive::compress(tar, request.timestamp, name)?;
    Ok(encryption::seal(&gzip, request.user_public_key)?)
}

fn sha256(bytes: &[u8]) -> [u8; 32] {
    ring::digest::digest(&ring::digest::SHA256, bytes)
        .as_ref()
        .try_into()
        .expect("SHA-256 produces 32 bytes")
}
