[package]
name = "header-parsing"
version = "0.0.3"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"
edition = "2021"
rust-version = "1.74.0"
description = "Common header parsing functionality"

[dependencies]
http = "0.2"
