[package]
name = "orb-ipcp-hpke"
version = "0.1.0"
description = "Shared iPCP HPKE encryption and decryption"
publish = false
edition = "2024"
rust-version = "1.93"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"

[dependencies]
getrandom = "0.4"
hpke = { version = "=0.14.1", default-features = false, features = ["x25519", "aes"] }
rand_core = "0.10.1"
sha2 = "0.10.8"
thiserror = "2.0.17"
zeroize = "1.8.2"

[dev-dependencies]
hex = "0.4.3"
serde_json = "1"
