[package]
name = "orb-blob-transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
iroh = "0.90.0"
iroh-blobs = "0.91.0"
