[package]
name = "orb-sound"
version = "0.0.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alsa-sys = "0.3.1"
futures.workspace = true
libc.workspace = true
riff = "2"
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
color-eyre.workspace = true
tokio.workspace = true
