## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
history_filter = [
  "CACHIX_AUTH_TOKEN=",
  "GITHUB_TOKEN=",
  "MEMFAULT_AUTH_TOKEN=",
  "MY_SECRET=",
  "OPENAI_API_KEY=",
  "ORB_MANAGER_INTERNAL_TOKEN=",
  "TOKEN=",
  "cachix authtoken",
  "export AWS_(ACCESS_KEY_ID|SECRET_ACCESS_KEY|SESSION_TOKEN)=",
  "gt auth --token",
]
