# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$hostname\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
format = "[ $path ]($style)"
style = "fg:#e3e5e5 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

[nodejs]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[rust]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[golang]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = "ﳑ"

[php]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[time]
disabled = false
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
style = "bg:#1d2230"
time_format = "%R" # Hour:Minute Format

[os]
disabled = false
format = '[ $symbol ]($style)'
style = "bg:#a3aed2 fg:#090c0c"

[os.symbols]
Macos = " "
Ubuntu = " "

[hostname]
format = '[$hostname]($style)'
ssh_only = true
style = "bg:#a3aed2 fg:#090c0c"
