[package]
name = "problematic-libs"
version = "0.0.3"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"
edition = "2021"
rust-version = "1.73.0"
description = "Smoke test for problematic libraries"

[dependencies]
rodio = "0.17"
ring = "0.17"
nix = "0.27"
libc = "0.2"
# The `use-pkg-config` feature flag is mandatory, because I was not able to get
# the libsodium-sys-stable build script to cross compile. Instead, we use a
# precompiled version provided by a package manager, and detect it with pkg-config.
# This also dramatically reduces compile times, as libsodium takes ages to build.
alkali = { version = "0.3", features = ["use-pkg-config"] }
openssl = "0.10"

[target.'cfg(target_os = "linux")'.dependencies]
seek-camera = { git = "https://github.com/worldcoin/orb-core", rev = "6dae83f" }
alsa = "0.8"
