[package]
name = "agentwire-macros"
version = "0.0.1"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = """
Procedural macros for agentwire.
"""
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "2.0.55", features = ["extra-traits"] }
