syntax = "proto3";

package pcp.v1;

message IrisCodeShares {
  optional string iris_version = 1 [json_name = "IRIS_version"];
  optional string iris_shares_version = 2 [json_name = "IRIS_shares_version"];
  optional string left_iris_code_shares = 3 [json_name = "left_iris_code_shares"];
  optional string left_mask_code_shares = 4 [json_name = "left_mask_code_shares"];
  optional string right_iris_code_shares = 5 [json_name = "right_iris_code_shares"];
  optional string right_mask_code_shares = 6 [json_name = "right_mask_code_shares"];
}
