[package]
name = "orb-agent-iroh"
version = "0.0.0"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
description = """
An orb-core agent that provides peer-to-peer QUIC capabilities
"""
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
agentwire.workspace = true
# the same version that iroh uses. this is only here to provide conversions
anyhow = "1.0.98" 
bon.workspace = true
derive_more = { workspace = true, features = ["from", "into", "display"] }
eyre.workspace = true
flume.workspace = true
iroh = { workspace = true, default-features = true } # TODO: fine grained features
n0-future = "0.1.3"
n0-watcher = "0.2.0"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
color-eyre.workspace = true
futures.workspace = true
tokio-util.workspace = true
tracing-subscriber.workspace = true

[package.metadata.orb]
unsupported_targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
