[package]
name = "seek-camera-sys"
version = "0.0.0"
description = "Low-level bindings for the seek thermal camera SDK"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

[build-dependencies]
bindgen = "0.69"
color-eyre = "0.6"
convert_case = "0.6"

[package.metadata.orb]
unsupported_targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]
