[package]
name = "orb-update-verifier"
version = "0.2.5"
description = """
Checks general system health and manages the slot and rootfs state of the Orb.
"""
authors = [
	"Mark Eder <mark.eder@toolsforhumanity.com>",
	"Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>",
]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
can-rs.workspace = true
clap = { workspace = true, features = ["derive"] }
eyre = "0.6.8"
flume = "0.11.0"
jod-thread = "0.1.2"
libc = "0.2.137"
log = "0.4.18"
orb-build-info.workspace = true
orb-messages.workspace = true
orb-slot-ctrl.workspace = true
polling = "2.2.0"
prost = "0.12.4"
semver = "1.0.22"
tap = "1.0.1"
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-journald.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zbus.workspace = true
zbus_systemd = { workspace = true, features = ["login1"] }

[dependencies.reqwest]
workspace = true
default-features = false
features = ["blocking", "json"]

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[dev-dependencies]
serde = { version = "1.0.147", features = ["derive"] }
# isahc = { version = "1.7", features = ["static-ssl"] }
httpmock = "0.7"
serde_json = "1.0.94"
prost-build = "0.12.4"

[package.metadata.orb]
unsupported_targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [
  ["target/release/orb-update-verifier", "/usr/local/bin/", "755"]
]
systemd-units = [
  { unit-name = "worldcoin-update-verifier" },
]
