[package]
name = "orb-update-verifier"
version = "0.2.6"
description = """
Checks general system health and manages the slot and rootfs state of the Orb.
"""
authors = [
	"Mark Eder <mark.eder@toolsforhumanity.com>",
	"Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>",
]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
can-rs.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
flume = "0.11.0"
jod-thread = "0.1.2"
libc.workspace = true
orb-build-info.workspace = true
orb-messages.workspace = true
orb-slot-ctrl.workspace = true
orb-telemetry.workspace = true
polling = "2.2.0"
prost = "0.12.6"
semver = "1.0.22"
tap = "1.0.1"
thiserror.workspace = true
tracing.workspace = true
zbus.workspace = true
zbus_systemd = { workspace = true, features = ["login1"] }

[dependencies.reqwest]
workspace = true
default-features = false
features = ["blocking", "json"]

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[dev-dependencies]
# isahc = { version = "1.7", features = ["static-ssl"] }
httpmock = "0.7"
prost-build = "0.12.6"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[package.metadata.orb]
unsupported_targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [
  ["target/release/orb-update-verifier", "/usr/local/bin/", "755"]
]
systemd-units = [
  { unit-name = "worldcoin-update-verifier" },
]
