[package]
name = "orb-tools"
version = "0.0.0"
description = "One-stop shop for orb developer tooling"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
orb-bidiff-cli.workspace = true
orb-build-info.workspace = true
orb-telemetry.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }
