[package]
name = "orb-blob-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true, default-features = false, features = ["json"] }
axum = { workspace = true, features = ["macros"] }
bon.workspace = true
clap.workspace = true
color-eyre.workspace = true
futures-lite = "2.6.0"
iroh = { version = "0.91.0", features = ["discovery-local-network", "discovery-pkarr-dht"] }
iroh-blobs = "0.93.0"
iroh-gossip = "0.91.0"
orb-blob-p2p.workspace = true
orb-blob.workspace = true
orb-build-info.workspace = true
orb-telemetry.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
tracing-subscriber.workspace = true

[dependencies.sqlx]
workspace = true
features = ["runtime-tokio-rustls", "macros", "migrate", "sqlite"]

[dev-dependencies]
async-tempfile.workspace = true
tracing.workspace = true

[package.metadata.orb]
unsupported_targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
