[package]
name = "build-info-helper"
version = "0.0.4"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"
edition = "2021"
rust-version = "1.75.0"
description = "Detects build information, makes it available for use"

[dependencies]
color-eyre = "0.6"
