[package]
name = "build-info-helper"
version = "0.0.4"
description = "Detects build information, makes it available for use"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre = "0.6"
