[package]
name        = "orb-update-common"
version     = "0.0.0"
description = "Common utilities for update progress handling across orb components"
authors     = ["Worldcoin Team"]
publish     = false

edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }

[dependencies]
orb-update-agent-dbus   = { workspace = true }
zbus                    = { workspace = true, default-features = false }
thiserror               = { workspace = true }

[dev-dependencies]
eyre         = { workspace = true }
tokio        = { workspace = true } 
