name: Proto CI
on:
  pull_request:
    paths:
      - 'pcp-defs/**'
      - '.github/workflows/proto-ci.yaml'
  workflow_dispatch:
  workflow_call:
    secrets:
      ORB_GIT_HUB_TOKEN:
        required: true
      CACHIX_AUTH_TOKEN:
        required: false
  push:
    branches:
      - main
      - prod
    paths:
      - 'pcp-defs/**'
      - '.github/workflows/proto-ci.yaml'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on:
      group: arc-public-xlarge-amd64-runner
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
        with:
          token: ${{ secrets.ORB_GIT_HUB_TOKEN }}
      - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # pin@v31.8.4
        with:
          github_access_token: ${{ secrets.ORB_GIT_HUB_TOKEN }}
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # pin@v15
        continue-on-error: true
        with:
          name: worldcoin
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Print environment
        run: |
          uname -a
          nix develop -c env

      - name: buf lint
        working-directory: pcp-defs
        run: nix develop -c buf lint

  format:
    name: Format
    runs-on:
      group: arc-public-xlarge-amd64-runner
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
        with:
          token: ${{ secrets.ORB_GIT_HUB_TOKEN }}
      - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # pin@v31.8.4
        with:
          github_access_token: ${{ secrets.ORB_GIT_HUB_TOKEN }}
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # pin@v15
        continue-on-error: true
        with:
          name: worldcoin
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: buf format
        working-directory: pcp-defs
        run: nix develop -c buf format --diff --exit-code
