name: Safe Test Workflow

on:
  push:
    branches:
      - test-branch   # push yaptığın branch'i yaz

jobs:
  safe-whoami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run whoami and save to file
        run: |
          whoami > whoami.txt
          echo "Saved whoami to whoami.txt"

      - name: Show whoami in job log
        run: |
          echo "---- whoami output ----"
          cat whoami.txt
          echo "-----------------------"

      - name: Upload whoami output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: whoami-output
          path: whoami.txt
