# Github workflow for update-agent

name: update-agent

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    secrets:
      ORB_GIT_HUB_TOKEN:
        required: true
  push:
    branches:
      - main
      - prod
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt update && sudo apt install -y \
            qemu-system-x86 qemu-utils \
            podman \
            squashfs-tools \
            parted e2fsprogs \
            genisoimage \
            libguestfs-tools pkg-config \
            libssl-dev build-essential \
            cargo libudev-dev protobuf-compiler \
            ovmf

      - name: Install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # pin@v2.2.0
        with:
          bun-version: 1.2.10

      - name: make host kernel image readable, for guestfish
        run: sudo chmod +r /boot/vmlinuz-*

      - name: guestfish access to kvm
        run: sudo chmod 0666 /dev/kvm

      - name: Build
        run: |
          cd update-agent
          cargo build --features skip-manifest-signature-verification

      - name: Run functional tests
        run: |
          cd update-agent/t
          ./qemu-runner.js mock mock_path
          ./qemu-runner.js run ../../target/debug/orb-update-agent mock_path
          ./qemu-runner.js check mock_path
