[package]
name = "thermal-cam-util"
version = "0.0.3"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"
edition = "2021"
rust-version = "1.73.0"
description = "Utilities for the thermal camera on the orb"

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
clap = { version = "4.3", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6"
indicatif = "0.17"
owo-colors = "3"
png = "0.17"
seek-camera = { git = "https://github.com/worldcoin/orb-core", rev = "6dae83f" }

[build-dependencies]
color-eyre = "0.6.2"
